-- MySQL Script generated by MySQL Workbench
-- Sat Dec 10 01:04:09 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estacionamentoCRUD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estacionamentoCRUD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estacionamentoCRUD` DEFAULT CHARACTER SET utf8 ;
USE `estacionamentoCRUD` ;

-- -----------------------------------------------------
-- Table `estacionamentoCRUD`.`estacionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionamentoCRUD`.`estacionamento` (
  `idEstacionamento` INT NOT NULL AUTO_INCREMENT,
  `vaga` INT NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstacionamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estacionamentoCRUD`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estacionamentoCRUD`.`veiculo` (
  `idveiculo` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `estacionamento_idEstacionamento` INT NOT NULL,
  PRIMARY KEY (`idveiculo`, `estacionamento_idEstacionamento`),
  INDEX `fk_veiculo_estacionamento_idx` (`estacionamento_idEstacionamento` ASC) VISIBLE,
  CONSTRAINT `fk_veiculo_estacionamento`
    FOREIGN KEY (`estacionamento_idEstacionamento`)
    REFERENCES `estacionamentoCRUD`.`estacionamento` (`idEstacionamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
